name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - vuepress
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: vuepress
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20.3.1'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Install dependencies
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUB_TOKEN }}
          publish_dir: ./dist
