name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - vuepress
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: vuepress
      - uses: borales/actions-yarn@v3
        with:
          cmd: install
      - uses: borales/actions-yarn@v3
        with:
          cmd: build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUB_TOKEN }}
          publish_dir: ./dist
