name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - vuepress
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: vuepress
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - uses: borales/actions-yarn@v4
        with:
          cmd: deploy
